chore: revert to using drafts befre finalizing bcr publish (#307)
Removing this caused:
```
Error: Failed to upload release asset source.json.intoto.jsonl. received status code 422
```

### Changes are visible to end-users: no

### Test plan

- Covered by existing test cases